"""
modules/terminology.py — قاموس سياقي شامل لـ 73 نشاطاً تجارياً

كل نشاط تجاري له "هوية برمجية" كاملة:
  ● المصطلحات اللغوية: فاتورة ← وصفة (صيدلية)، طلب ← أمر إصلاح (ورشة)
  ● شخصية الموظف: بائع ← صيدلي ← فني ← نادل ← مسوّق
  ● واجهة POS: pos_mode يتحكم في شكل الشاشة كلياً
  ● أيقونة + وصف القطاع: تظهر في لوحة التحكم والتقارير

مفاتيح pos_mode:
  standard     → تجزئة عامة (باركود + سلة)
  restaurant   → مطعم/كافيه (صور + طاولات + مطبخ)
  pharmacy     → صيدلية (باركود + تاريخ صلاحية + مريض)
  workshop     → ورشة (أوامر إصلاح + فني + مركبة)
  fashion      → أزياء (مقاس/لون + كولكشن)
  wholesale    → جملة (كرتون/طن + موزع + تسعير كمية)
  construction → مقاولات (مشاريع + مستخلصات)
  rental       → تأجير (أسطول + عقود + أيام)
  medical      → عيادة (مواعيد + مريض + طبيب)
"""

# ── المصطلحات الافتراضية لكل نشاط لم يُحدَّد ────────────────────────────────
_DEFAULT = {
    # ─ الكيانات الأساسية ─────────────────────────────────────
    "invoice":          "فاتورة",
    "order":            "طلب",
    "product":          "منتج",
    "products":         "منتجات",
    "category":         "تصنيف",
    "customer":         "عميل",
    "customers":        "عملاء",
    "supplier":         "مورد",
    "suppliers":        "موردون",
    "item":             "صنف",
    "items":            "أصناف",
    "service":          "خدمة",
    "services":         "خدمات",
    "project":          "مشروع",
    "work_order":       "أمر عمل",
    # ─ الأرقام والقياسات ──────────────────────────────────────
    "quantity":         "الكمية",
    "unit":             "وحدة",
    "price":            "السعر",
    "total":            "الإجمالي",
    "subtotal":         "المجموع قبل الضريبة",
    "tax":              "الضريبة",
    "discount":         "الخصم",
    "payment":          "الدفع",
    "receipt":          "إيصال",
    "expiry":           "تاريخ الانتهاء",
    "serial":           "الرقم التسلسلي",
    "barcode":          "باركود",
    "variant":          "نوع / مقاس",
    # ─ المواقع والموارد ───────────────────────────────────────
    "warehouse":        "مستودع",
    "stock":            "المخزون",
    "table":            "طاولة",
    "tables":           "طاولات",
    "kitchen":          "المطبخ",
    "recipe":           "وصفة",
    "branch":           "فرع",
    # ─ الأفعال والأوامر ───────────────────────────────────────
    "sale":             "بيع",
    "sales":            "المبيعات",
    "purchase":         "مشتريات",
    "new_invoice":      "فاتورة جديدة",
    "new_order":        "طلب جديد",
    "new_sale":         "بيع جديد",
    "add_product":      "إضافة منتج",
    # ─ الأدوار والأشخاص ───────────────────────────────────────
    "cashier":          "كاشير",
    "seller":           "بائع",
    "employee":         "موظف",
    # ─ الحالات ────────────────────────────────────────────────
    "notes":            "ملاحظات",
    "status_paid":      "مدفوع",
    "status_pending":   "معلق",
    "status_draft":     "مسودة",
    # ─ التنقل ─────────────────────────────────────────────────
    "pos":              "نقطة البيع",
    "dashboard":        "لوحة التحكم",
    "reports":          "التقارير",
    "accounting":       "المحاسبة",
    "settings":         "الإعدادات",
    # ─ مفاتيح واجهة المستخدم (UI control) ────────────────────
    "pos_mode":         "standard",
    "pos_search_hint":  "ابحث بالاسم أو الباركود...",
    "pos_quick_label":  "بيع سريع",
    "industry_icon":    "🏪",
    "industry_label":   "نشاط تجاري",
}

# ═══════════════════════════════════════════════════════════════════════════════
# القاموس الشامل — 73 نشاطاً تجارياً
# ═══════════════════════════════════════════════════════════════════════════════
_SECTOR_TERMS: dict[str, dict] = {

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تقديم الطعام — المطاعم والكافيهات
    # ══════════════════════════════════════════════════════════════════════════
    "food_restaurant": {
        "product":         "طبق",
        "products":        "قائمة الطعام",
        "category":        "قسم الطعام",
        "order":           "طلب الطاولة",
        "invoice":         "فاتورة الطاولة",
        "new_order":       "طلب طاولة جديد",
        "new_sale":        "فتح طلب",
        "item":            "صنف",
        "items":           "أصناف الطلب",
        "customer":        "ضيف",
        "customers":       "الضيوف",
        "seller":          "نادل",
        "employee":        "موظف خدمة",
        "unit":            "حصة",
        "recipe":          "وصفة الطبق",
        "warehouse":       "المطبخ",
        "stock":           "مخزون المطبخ",
        "kitchen":         "قسم التحضير",
        "quantity":        "الكمية المطلوبة",
        "table":           "الطاولة",
        "tables":          "الطاولات",
        "pos_mode":        "restaurant",
        "pos_search_hint": "ابحث بالطبق أو القسم...",
        "pos_quick_label": "طلب طاولة",
        "industry_icon":   "🍽️",
        "industry_label":  "مطعم",
    },
    "food_cafe": {
        "product":         "مشروب / منتج",
        "products":        "قائمة الكافيه",
        "category":        "نوع المشروب",
        "order":           "طلب",
        "invoice":         "فاتورة الكافيه",
        "new_order":       "طلب جديد",
        "new_sale":        "تسجيل طلب",
        "item":            "صنف",
        "customer":        "ضيف",
        "customers":       "الضيوف",
        "seller":          "باريستا",
        "employee":        "موظف خدمة",
        "unit":            "كوب",
        "warehouse":       "المخزن",
        "stock":           "مخزون الكافيه",
        "kitchen":         "بار التحضير",
        "pos_mode":        "restaurant",
        "pos_search_hint": "ابحث بالمشروب أو الصنف...",
        "pos_quick_label": "طلب كافيه",
        "industry_icon":   "☕",
        "industry_label":  "كافيه",
    },
    "food_coffeeshop": {
        "product":         "قهوة / مشروب",
        "products":        "قائمة المقهى",
        "category":        "نوع",
        "order":           "طلب",
        "invoice":         "فاتورة المقهى",
        "new_sale":        "تسجيل طلب",
        "item":            "صنف",
        "customer":        "زبون",
        "seller":          "مُعدّ القهوة",
        "unit":            "كوب",
        "warehouse":       "مخزن المقهى",
        "stock":           "مخزون البن والمستلزمات",
        "kitchen":         "بار التحضير",
        "pos_mode":        "restaurant",
        "pos_search_hint": "ابحث بنوع القهوة...",
        "pos_quick_label": "تسجيل طلب",
        "industry_icon":   "☕",
        "industry_label":  "مقهى",
    },
    "food_hookah": {
        "product":         "خلطة / وصفة",
        "products":        "قائمة المعسل",
        "category":        "نوع المعسل",
        "order":           "طلب المعسل",
        "invoice":         "فاتورة المعسل",
        "new_order":       "طلب معسل جديد",
        "new_sale":        "تسجيل طلب",
        "item":            "معسل",
        "items":           "طلبات المعسل",
        "customer":        "ضيف",
        "seller":          "موظف",
        "recipe":          "خلطة",
        "unit":            "رأس",
        "warehouse":       "مخزن المعسل",
        "stock":           "مخزون المعسل",
        "kitchen":         "غرفة التحضير",
        "pos_mode":        "restaurant",
        "pos_search_hint": "ابحث بنوع المعسل...",
        "pos_quick_label": "طلب معسل",
        "industry_icon":   "💨",
        "industry_label":  "معسلات",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجزئة — غذاء وتموين
    # ══════════════════════════════════════════════════════════════════════════
    "retail_fnb_supermarket": {
        "product":         "صنف",
        "products":        "أصناف السوبر ماركت",
        "category":        "رف / قسم",
        "item":            "صنف",
        "items":           "أصناف",
        "unit":            "حبة / عبوة",
        "warehouse":       "المستودع / الرف",
        "stock":           "مخزون السوبر ماركت",
        "new_sale":        "بيع جديد",
        "expiry":          "تاريخ الصلاحية",
        "seller":          "بائع",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالاسم أو الباركود أو الرف...",
        "pos_quick_label": "بيع سريع",
        "industry_icon":   "🛒",
        "industry_label":  "سوبر ماركت",
    },
    "retail_fnb_grocery": {
        "product":         "صنف",
        "products":        "أصناف البقالة",
        "category":        "تصنيف",
        "unit":            "حبة / كغ",
        "expiry":          "تاريخ الصلاحية",
        "seller":          "صاحب البقالة",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالاسم أو الباركود...",
        "pos_quick_label": "بيع سريع",
        "industry_icon":   "🏬",
        "industry_label":  "بقالة / تموينات",
    },
    "retail_fnb_roaster": {
        "product":         "صنف محمّص",
        "products":        "منتجات المحمصة",
        "category":        "نوع المنتج",
        "unit":            "كغ",
        "recipe":          "خلطة التحميص",
        "seller":          "صاحب المحمصة",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالنوع أو المصنع...",
        "pos_quick_label": "بيع بالكيلو",
        "industry_icon":   "☕",
        "industry_label":  "محمصة",
    },
    "retail_fnb_bakery": {
        "product":         "منتج مخبز",
        "products":        "منتجات المخبز",
        "category":        "نوع المنتج",
        "recipe":          "وصفة الخبز",
        "unit":            "قطعة / كغ",
        "warehouse":       "مخزن المواد الخام",
        "stock":           "مخزون المواد",
        "seller":          "صراف المخبز",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالمنتج أو الصنف...",
        "pos_quick_label": "بيع منتجات",
        "industry_icon":   "🥖",
        "industry_label":  "مخبز",
    },
    "retail_fnb_butcher": {
        "product":         "قطعة لحم",
        "products":        "أنواع اللحوم",
        "category":        "نوع اللحم",
        "unit":            "كغ",
        "item":            "قطعة",
        "stock":           "المخزون الطازج",
        "seller":          "جزار",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بنوع اللحم...",
        "pos_quick_label": "بيع بالكيلو",
        "industry_icon":   "🥩",
        "industry_label":  "ملحمة / جزارة",
    },
    "retail_fnb_produce": {
        "product":         "صنف طازج",
        "products":        "الخضار والفواكه",
        "category":        "نوع",
        "unit":            "كغ / حبة",
        "stock":           "مخزون اليوم",
        "seller":          "بائع خضار",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالصنف...",
        "pos_quick_label": "بيع بالكيلو",
        "industry_icon":   "🥦",
        "industry_label":  "خضار وفواكه",
    },
    "retail_fnb_dates": {
        "product":         "نوع تمر",
        "products":        "أنواع التمور",
        "category":        "الصنف والمنشأ",
        "unit":            "كغ / صندوق",
        "stock":           "مخزون التمور",
        "seller":          "تاجر تمور",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بنوع التمر أو المنشأ...",
        "pos_quick_label": "بيع تمور",
        "industry_icon":   "🌴",
        "industry_label":  "تجار التمور",
    },
    "retail_fnb_beverages": {
        "product":         "مشروب / عبوة",
        "products":        "المشروبات",
        "category":        "نوع المشروب",
        "unit":            "عبوة / كرتون",
        "expiry":          "تاريخ الصلاحية",
        "stock":           "مخزون المشروبات",
        "seller":          "بائع",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالاسم أو الباركود...",
        "pos_quick_label": "بيع مشروبات",
        "industry_icon":   "🧃",
        "industry_label":  "مياه ومشروبات",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجزئة — موضة وملبوسات
    # ══════════════════════════════════════════════════════════════════════════
    "retail_fashion_clothing_m": {
        "product":         "قطعة ملابس رجالي",
        "products":        "ملابس رجالي",
        "category":        "المجموعة / النوع",
        "item":            "قطعة",
        "items":           "قطع",
        "unit":            "قطعة",
        "variant":         "مقاس / لون",
        "customer":        "عميل",
        "seller":          "بائع أزياء",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالاسم أو الكود أو المقاس...",
        "pos_quick_label": "بيع قطعة",
        "industry_icon":   "👔",
        "industry_label":  "ملابس رجالي",
    },
    "retail_fashion_clothing_f": {
        "product":         "قطعة ملابس نسائي",
        "products":        "ملابس نسائي",
        "category":        "الكولكشن / النوع",
        "item":            "قطعة",
        "items":           "قطع",
        "unit":            "قطعة",
        "variant":         "مقاس / لون",
        "customer":        "عميلة",
        "customers":       "العميلات",
        "seller":          "بائعة أزياء",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحثي بالاسم أو الكولكشن...",
        "pos_quick_label": "بيع قطعة",
        "industry_icon":   "👗",
        "industry_label":  "ملابس نسائي",
    },
    "retail_fashion_clothing_k": {
        "product":         "قطعة ملابس أطفال",
        "products":        "ملابس أطفال",
        "category":        "العمر / المقاس",
        "unit":            "قطعة",
        "variant":         "مقاس / عمر",
        "seller":          "بائع",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالاسم أو المقاس...",
        "pos_quick_label": "بيع قطعة",
        "industry_icon":   "👶",
        "industry_label":  "ملابس أطفال",
    },
    "retail_fashion_shoes": {
        "product":         "حذاء",
        "products":        "أحذية",
        "category":        "النوع / الجنس",
        "unit":            "زوج",
        "item":            "زوج",
        "variant":         "مقاس",
        "seller":          "بائع أحذية",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالاسم أو المقاس...",
        "pos_quick_label": "بيع زوج",
        "industry_icon":   "👟",
        "industry_label":  "أحذية",
    },
    "retail_fashion_bags": {
        "product":         "حقيبة / إكسسوار",
        "products":        "حقائب وإكسسوارات",
        "category":        "النوع / الماركة",
        "unit":            "قطعة",
        "variant":         "اللون / الحجم",
        "seller":          "بائع",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالنوع أو الكود...",
        "pos_quick_label": "بيع حقيبة",
        "industry_icon":   "👜",
        "industry_label":  "حقائب وإكسسوارات",
    },
    "retail_fashion_watches": {
        "product":         "ساعة / مجوهر",
        "products":        "ساعات ومجوهرات",
        "category":        "النوع / الماركة",
        "unit":            "قطعة",
        "variant":         "الحجم / المادة",
        "seller":          "بائع مجوهرات",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالاسم أو الماركة...",
        "pos_quick_label": "بيع قطعة",
        "industry_icon":   "⌚",
        "industry_label":  "ساعات ومجوهرات",
    },
    "retail_fashion_optics": {
        "product":         "نظارة / عدسة",
        "products":        "النظارات والعدسات",
        "category":        "النوع / الإطار",
        "unit":            "قطعة",
        "variant":         "مقاس الإطار / القوة",
        "customer":        "عميل",
        "seller":          "أخصائي بصريات",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالإطار أو الوصفة الطبية...",
        "pos_quick_label": "بيع نظارة",
        "industry_icon":   "👓",
        "industry_label":  "نظارات وبصريات",
    },
    "retail_fashion_fabric": {
        "product":         "قماش",
        "products":        "الأقمشة",
        "category":        "نوع القماش",
        "unit":            "متر",
        "variant":         "اللون / العرض",
        "seller":          "تاجر أقمشة",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بنوع القماش أو اللون...",
        "pos_quick_label": "بيع بالمتر",
        "industry_icon":   "🧵",
        "industry_label":  "أقمشة ومنسوجات",
    },
    "retail_fashion_tailoring": {
        "product":         "خامة / مستلزم خياطة",
        "products":        "مستلزمات الخياطة",
        "category":        "نوع المستلزم",
        "unit":            "قطعة / متر",
        "seller":          "بائع مستلزمات",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالصنف...",
        "pos_quick_label": "بيع مستلزم",
        "industry_icon":   "✂️",
        "industry_label":  "مستلزمات خياطة",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجزئة — مواد بناء وأدوات
    # ══════════════════════════════════════════════════════════════════════════
    "retail_construction_materials": {
        "product":         "مادة بناء",
        "products":        "مواد البناء",
        "category":        "التصنيف",
        "unit":            "كيس / م² / طن",
        "warehouse":       "المستودع",
        "stock":           "المخزون",
        "seller":          "مندوب مبيعات",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالمادة أو الكود...",
        "pos_quick_label": "بيع مواد",
        "industry_icon":   "🏗️",
        "industry_label":  "مواد بناء",
    },
    "retail_construction_plumbing": {
        "product":         "أداة / قطعة سباكة",
        "products":        "أدوات السباكة",
        "category":        "نوع القطعة",
        "unit":            "قطعة / متر",
        "seller":          "بائع سباكة",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالقطعة أو الكود...",
        "pos_quick_label": "بيع أدوات",
        "industry_icon":   "🔧",
        "industry_label":  "سباكة وصحيات",
    },
    "retail_construction_electrical": {
        "product":         "قطعة كهربائية",
        "products":        "الأجهزة والأدوات الكهربائية",
        "category":        "نوع القطعة",
        "unit":            "قطعة / متر",
        "expiry":          "—",
        "seller":          "بائع كهربائيات",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالقطعة أو المواصفة...",
        "pos_quick_label": "بيع كهرباء",
        "industry_icon":   "💡",
        "industry_label":  "كهرباء وإنارة",
    },
    "retail_construction_paints": {
        "product":         "دهان / طلاء",
        "products":        "الدهانات والطلاءات",
        "category":        "النوع والماركة",
        "unit":            "كيلو / لتر / سطل",
        "variant":         "اللون",
        "seller":          "بائع دهانات",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث باللون أو الماركة...",
        "pos_quick_label": "بيع دهان",
        "industry_icon":   "🎨",
        "industry_label":  "دهانات",
    },
    "retail_construction_flooring": {
        "product":         "بلاطة / رخامة",
        "products":        "الأرضيات والسيراميك",
        "category":        "النوع والتصميم",
        "unit":            "م²",
        "variant":         "الحجم / الديكور",
        "seller":          "مندوب مبيعات",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالتصميم أو المواصفة...",
        "pos_quick_label": "بيع أرضيات",
        "industry_icon":   "🏠",
        "industry_label":  "أرضيات وسيراميك",
    },
    "retail_construction_hardware": {
        "product":         "عدة / أداة",
        "products":        "العدد والأدوات",
        "category":        "نوع الأداة",
        "unit":            "قطعة / طقم",
        "serial":          "السيريال",
        "seller":          "بائع عدد",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالأداة أو الماركة...",
        "pos_quick_label": "بيع عدة",
        "industry_icon":   "🔨",
        "industry_label":  "عدد وأدوات",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجزئة — إلكترونيات وتقنية
    # ══════════════════════════════════════════════════════════════════════════
    "retail_electronics_mobile": {
        "product":         "جوال / إكسسوار",
        "products":        "الجوالات والإكسسوارات",
        "category":        "الماركة / النوع",
        "unit":            "جهاز / قطعة",
        "serial":          "IMEI / السيريال",
        "variant":         "اللون / الذاكرة",
        "seller":          "مندوب مبيعات",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالاسم أو IMEI أو الباركود...",
        "pos_quick_label": "بيع جوال",
        "industry_icon":   "📱",
        "industry_label":  "جوالات وإكسسوارات",
    },
    "retail_electronics_computers": {
        "product":         "جهاز / قطعة تقنية",
        "products":        "الأجهزة وقطع التقنية",
        "category":        "النوع / الماركة",
        "unit":            "جهاز / قطعة",
        "serial":          "السيريال",
        "variant":         "المواصفات",
        "seller":          "مختص تقنية",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالاسم أو المواصفة...",
        "pos_quick_label": "بيع جهاز",
        "industry_icon":   "💻",
        "industry_label":  "كمبيوتر ولابتوب",
    },
    "retail_electronics_appliances": {
        "product":         "جهاز منزلي",
        "products":        "الأجهزة المنزلية",
        "category":        "النوع / الماركة",
        "unit":            "جهاز",
        "serial":          "السيريال",
        "variant":         "المقاس / المواصفة",
        "seller":          "مندوب مبيعات",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالجهاز أو الماركة...",
        "pos_quick_label": "بيع جهاز",
        "industry_icon":   "🏠",
        "industry_label":  "أجهزة منزلية",
    },
    "retail_electronics_entertainment": {
        "product":         "جهاز ترفيهي / لعبة",
        "products":        "الترفيه والألعاب الإلكترونية",
        "category":        "النوع / المنصة",
        "unit":            "جهاز / نسخة",
        "serial":          "السيريال",
        "seller":          "بائع",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالجهاز أو اللعبة...",
        "pos_quick_label": "بيع جهاز",
        "industry_icon":   "🎮",
        "industry_label":  "إلكترونيات ترفيهية",
    },
    "retail_electronics_security": {
        "product":         "كاميرا / نظام أمني",
        "products":        "أنظمة المراقبة والأمن",
        "category":        "النوع",
        "unit":            "جهاز / مجموعة",
        "serial":          "السيريال",
        "customer":        "عميل",
        "seller":          "مهندس أمني",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالنوع أو الكود...",
        "pos_quick_label": "بيع نظام",
        "industry_icon":   "📹",
        "industry_label":  "كاميرات وأمن",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجزئة — صحة وعناية ← أهم قطاع: الصيدلية بهوية كاملة
    # ══════════════════════════════════════════════════════════════════════════
    "retail_health_pharmacy": {
        "product":         "دواء / مستحضر",
        "products":        "قائمة الأدوية",
        "category":        "تصنيف الدواء",
        "invoice":         "فاتورة صيدلية",
        "order":           "وصفة طبية",
        "new_order":       "صرف وصفة",
        "new_sale":        "صرف دواء",
        "new_invoice":     "فاتورة صيدلية جديدة",
        "add_product":     "إضافة دواء",
        "item":            "دواء",
        "items":           "أدوية",
        "customer":        "مريض",
        "customers":       "المرضى",
        "seller":          "صيدلي",
        "employee":        "صيدلاني",
        "cashier":         "صيدلي الصراف",
        "unit":            "علبة / شريط / حبة",
        "expiry":          "تاريخ الصلاحية",
        "serial":          "رقم التشغيلة",
        "barcode":         "باركود الدواء",
        "warehouse":       "مخزن الأدوية",
        "stock":           "مخزون الصيدلية",
        "recipe":          "وصفة طبية",
        "purchase":        "مشتريات الأدوية",
        "supplier":        "شركة الأدوية",
        "suppliers":       "موردو الأدوية",
        "pos_mode":        "pharmacy",
        "pos_search_hint": "ابحث بالاسم التجاري أو العلمي أو الباركود...",
        "pos_quick_label": "صرف دواء",
        "industry_icon":   "💊",
        "industry_label":  "صيدلية",
    },
    "retail_health_perfume": {
        "product":         "عطر / بخور",
        "products":        "العطور والبخور",
        "category":        "نوع العطر",
        "unit":            "قطعة / مل",
        "variant":         "الحجم / النوع",
        "seller":          "عطار",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالاسم أو النوع...",
        "pos_quick_label": "بيع عطر",
        "industry_icon":   "🌹",
        "industry_label":  "عطور وبخور",
    },
    "retail_health_cosmetics": {
        "product":         "منتج تجميل",
        "products":        "مستحضرات التجميل",
        "category":        "نوع المنتج",
        "unit":            "قطعة / عبوة",
        "variant":         "الدرجة / اللون",
        "customer":        "عميلة",
        "customers":       "العميلات",
        "seller":          "موظف/ة مبيعات",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالمنتج أو الماركة...",
        "pos_quick_label": "بيع منتج",
        "industry_icon":   "💄",
        "industry_label":  "مستحضرات تجميل",
    },
    "retail_health_medical": {
        "product":         "مستلزم طبي",
        "products":        "المستلزمات الطبية",
        "category":        "نوع المستلزم",
        "unit":            "قطعة / علبة",
        "expiry":          "تاريخ الصلاحية",
        "serial":          "رقم التشغيلة",
        "customer":        "مريض / عميل",
        "seller":          "موظف مبيعات",
        "pos_mode":        "pharmacy",
        "pos_search_hint": "ابحث بالاسم أو الباركود...",
        "pos_quick_label": "بيع مستلزم",
        "industry_icon":   "🏥",
        "industry_label":  "مستلزمات طبية",
    },
    "retail_health_supplements": {
        "product":         "مكمل / مستحضر صحي",
        "products":        "المكملات الغذائية",
        "category":        "نوع المكمل",
        "unit":            "علبة / عبوة",
        "expiry":          "تاريخ الصلاحية",
        "seller":          "أخصائي تغذية",
        "pos_mode":        "pharmacy",
        "pos_search_hint": "ابحث بالمكمل أو الفئة...",
        "pos_quick_label": "بيع مكمل",
        "industry_icon":   "💪",
        "industry_label":  "مكملات غذائية",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجزئة — سيارات ← الورشة بهوية كاملة
    # ══════════════════════════════════════════════════════════════════════════
    "retail_auto_parts": {
        "product":         "قطعة غيار",
        "products":        "قطع الغيار",
        "category":        "نوع القطعة / الشركة",
        "unit":            "قطعة",
        "serial":          "رقم القطعة",
        "barcode":         "باركود القطعة",
        "seller":          "بائع قطع غيار",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث برقم القطعة أو الاسم...",
        "pos_quick_label": "بيع قطعة",
        "industry_icon":   "⚙️",
        "industry_label":  "قطع غيار سيارات",
    },
    "retail_auto_tires": {
        "product":         "إطار / بطارية",
        "products":        "الإطارات والبطاريات",
        "category":        "النوع والمقاس",
        "unit":            "قطعة",
        "variant":         "المقاس / الماركة",
        "seller":          "بائع إطارات",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالمقاس أو الماركة...",
        "pos_quick_label": "بيع إطار",
        "industry_icon":   "🔄",
        "industry_label":  "إطارات وبطاريات",
    },
    "retail_auto_accessories": {
        "product":         "إكسسوار سيارة",
        "products":        "إكسسوارات السيارات",
        "category":        "النوع",
        "unit":            "قطعة / طقم",
        "seller":          "بائع",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالإكسسوار أو الكود...",
        "pos_quick_label": "بيع إكسسوار",
        "industry_icon":   "🚘",
        "industry_label":  "إكسسوارات سيارات",
    },
    "retail_auto_workshop": {
        "product":         "خدمة / قطعة غيار",
        "products":        "الخدمات وقطع الغيار",
        "category":        "نوع الخدمة",
        "invoice":         "فاتورة الإصلاح",
        "order":           "أمر الإصلاح",
        "new_order":       "أمر إصلاح جديد",
        "new_sale":        "تسجيل مركبة",
        "new_invoice":     "أمر إصلاح جديد",
        "add_product":     "إضافة خدمة",
        "item":            "خدمة / قطعة",
        "items":           "خدمات وقطع",
        "customer":        "صاحب المركبة",
        "customers":       "أصحاب المركبات",
        "seller":          "فني",
        "employee":        "فني صيانة",
        "cashier":         "محاسب الورشة",
        "unit":            "ساعة / قطعة",
        "work_order":      "أمر الإصلاح",
        "project":         "أمر الصيانة",
        "serial":          "رقم اللوحة",
        "pos_mode":        "workshop",
        "pos_search_hint": "ابحث بالخدمة أو رقم اللوحة...",
        "pos_quick_label": "أمر إصلاح جديد",
        "industry_icon":   "🔧",
        "industry_label":  "ورشة صيانة سيارات",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجزئة — منزل ومكتب
    # ══════════════════════════════════════════════════════════════════════════
    "retail_home_furniture": {
        "product":         "قطعة أثاث",
        "products":        "الأثاث والمفروشات",
        "category":        "النوع / الغرفة",
        "unit":            "قطعة / طقم",
        "variant":         "اللون / الخامة",
        "seller":          "مستشار مبيعات",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالقطعة أو الكود...",
        "pos_quick_label": "بيع أثاث",
        "industry_icon":   "🛋️",
        "industry_label":  "أثاث ومفروشات",
    },
    "retail_home_carpet": {
        "product":         "سجادة / لفة موكيت",
        "products":        "السجاد والموكيت",
        "category":        "النوع / الحجم",
        "unit":            "م² / لفة",
        "variant":         "اللون / الحجم",
        "seller":          "بائع سجاد",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالنوع أو الحجم...",
        "pos_quick_label": "بيع سجادة",
        "industry_icon":   "🪟",
        "industry_label":  "سجاد وموكيت",
    },
    "retail_home_kitchenware": {
        "product":         "أداة / أواني منزلية",
        "products":        "الأواني ولوازم المنزل",
        "category":        "النوع",
        "unit":            "قطعة / طقم",
        "seller":          "بائع",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالأداة أو النوع...",
        "pos_quick_label": "بيع أدوات",
        "industry_icon":   "🍳",
        "industry_label":  "أواني منزلية",
    },
    "retail_home_stationery": {
        "product":         "قرطاسية / كتاب",
        "products":        "القرطاسية والمكتبية",
        "category":        "النوع",
        "unit":            "قطعة / دزينة",
        "seller":          "بائع قرطاسية",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالاسم أو الكود...",
        "pos_quick_label": "بيع قرطاسية",
        "industry_icon":   "📚",
        "industry_label":  "مكتبات وقرطاسية",
    },
    "retail_home_office": {
        "product":         "أثاث مكتبي",
        "products":        "تجهيزات المكاتب",
        "category":        "النوع / الاستخدام",
        "unit":            "قطعة / طقم",
        "variant":         "الحجم / اللون",
        "customer":        "عميل مؤسسي",
        "seller":          "مستشار مبيعات",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالقطعة أو الكود...",
        "pos_quick_label": "بيع أثاث مكتبي",
        "industry_icon":   "🏢",
        "industry_label":  "تجهيزات مكاتب",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجزئة — أنشطة متخصصة
    # ══════════════════════════════════════════════════════════════════════════
    "retail_specialized_tobacco": {
        "product":         "خلطة / معسل",
        "products":        "قائمة المعسل والتبغ",
        "category":        "نوع المعسل",
        "unit":            "جرام / علبة",
        "variant":         "النكهة",
        "seller":          "موظف",
        "recipe":          "خلطة مميزة",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالنكهة أو الماركة...",
        "pos_quick_label": "بيع معسل",
        "industry_icon":   "💨",
        "industry_label":  "معسلات ومستلزمات تدخين",
    },
    "retail_specialized_flowers": {
        "product":         "باقة / زهور",
        "products":        "الزهور والهدايا",
        "category":        "النوع / المناسبة",
        "unit":            "باقة / قطعة",
        "variant":         "الحجم / الألوان",
        "customer":        "عميل",
        "seller":          "منسق هدايا",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالنوع أو المناسبة...",
        "pos_quick_label": "تنسيق هدية",
        "industry_icon":   "💐",
        "industry_label":  "زهور وهدايا",
    },
    "retail_specialized_toys": {
        "product":         "لعبة / هدية",
        "products":        "الألعاب والهدايا",
        "category":        "العمر / النوع",
        "unit":            "قطعة",
        "variant":         "العمر المناسب",
        "seller":          "بائع",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالاسم أو الفئة العمرية...",
        "pos_quick_label": "بيع لعبة",
        "industry_icon":   "🧸",
        "industry_label":  "ألعاب وهدايا",
    },
    "retail_specialized_pets": {
        "product":         "مستلزم / علف",
        "products":        "مستلزمات الحيوانات الأليفة",
        "category":        "نوع الحيوان",
        "unit":            "كغ / قطعة",
        "expiry":          "تاريخ الصلاحية",
        "seller":          "موظف",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالمنتج أو نوع الحيوان...",
        "pos_quick_label": "بيع مستلزم",
        "industry_icon":   "🐾",
        "industry_label":  "مستلزمات حيوانات أليفة",
    },
    "retail_specialized_sports": {
        "product":         "معدة رياضية",
        "products":        "المعدات الرياضية",
        "category":        "الرياضة / النوع",
        "unit":            "قطعة / طقم",
        "variant":         "المقاس / الحجم",
        "seller":          "موظف رياضة",
        "pos_mode":        "fashion",
        "pos_search_hint": "ابحث بالمعدة أو الرياضة...",
        "pos_quick_label": "بيع معدة",
        "industry_icon":   "⚽",
        "industry_label":  "معدات رياضية",
    },
    "retail_specialized_camping": {
        "product":         "لازمة رحلة / معدة",
        "products":        "لوازم الرحلات والصيد",
        "category":        "النشاط / النوع",
        "unit":            "قطعة / طقم",
        "seller":          "موظف",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالمعدة أو النشاط...",
        "pos_quick_label": "بيع لوازم",
        "industry_icon":   "⛺",
        "industry_label":  "لوازم رحلات وصيد",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ تجارة الجملة — كل الأنواع
    # ══════════════════════════════════════════════════════════════════════════
    "wholesale": {
        "product":         "صنف / شحنة",
        "products":        "الأصناف",
        "invoice":         "فاتورة جملة",
        "order":           "طلب شراء",
        "new_invoice":     "فاتورة جملة جديدة",
        "new_sale":        "بيع جملة",
        "item":            "صنف",
        "items":           "الأصناف",
        "customer":        "تاجر / موزع",
        "customers":       "الموزعون والتجار",
        "supplier":        "مورد / منتج",
        "suppliers":       "الموردون والمنتجون",
        "unit":            "كرتون / طن / لوح",
        "quantity":        "الكمية (كرتون)",
        "warehouse":       "المستودع الرئيسي",
        "seller":          "مندوب مبيعات",
        "employee":        "موظف مستودع",
        "pos_mode":        "wholesale",
        "pos_search_hint": "ابحث بكود الصنف أو الباركود...",
        "pos_quick_label": "بيع جملة",
        "industry_icon":   "🏭",
        "industry_label":  "تجارة جملة",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ■ قطاعات الخدمات الخاصة
    # ══════════════════════════════════════════════════════════════════════════
    "construction": {
        "product":         "مستلزم / مادة",
        "products":        "مستلزمات المشروع",
        "category":        "نوع العمل / البند",
        "invoice":         "مستخلص مدفوعات",
        "order":           "أمر توريد",
        "new_order":       "مستخلص جديد",
        "new_sale":        "فتح مستخلص",
        "new_invoice":     "مستخلص جديد",
        "item":            "بند عمل",
        "items":           "بنود العمل",
        "service":         "نشاط إنشائي",
        "customer":        "جهة المشروع",
        "customers":       "الجهات المتعاقدة",
        "supplier":        "مقاول فرعي",
        "suppliers":       "المقاولون الفرعيون",
        "seller":          "مهندس / مشرف",
        "employee":        "مهندس",
        "unit":            "م² / م³ / وحدة",
        "work_order":      "أمر العمل",
        "project":         "المشروع",
        "warehouse":       "موقع المشروع",
        "stock":           "مواد الموقع",
        "pos_mode":        "construction",
        "pos_search_hint": "ابحث بالبند أو المشروع...",
        "pos_quick_label": "مستخلص جديد",
        "industry_icon":   "🏗️",
        "industry_label":  "مقاولات وتشغيل",
    },
    "car_rental": {
        "product":         "مركبة",
        "products":        "الأسطول",
        "category":        "نوع المركبة",
        "invoice":         "عقد إيجار",
        "order":           "حجز",
        "new_order":       "حجز جديد",
        "new_sale":        "عقد إيجار جديد",
        "new_invoice":     "عقد إيجار جديد",
        "item":            "مركبة",
        "items":           "المركبات",
        "customer":        "مستأجر",
        "customers":       "المستأجرون",
        "seller":          "موظف استقبال",
        "employee":        "موظف",
        "unit":            "يوم / أسبوع",
        "serial":          "رقم اللوحة",
        "work_order":      "عقد الإيجار",
        "project":         "رحلة الإيجار",
        "warehouse":       "موقف السيارات",
        "stock":           "الأسطول المتاح",
        "pos_mode":        "rental",
        "pos_search_hint": "ابحث بنوع المركبة أو اللوحة...",
        "pos_quick_label": "حجز جديد",
        "industry_icon":   "🚗",
        "industry_label":  "تأجير سيارات",
    },
    "medical": {
        "product":         "خدمة طبية",
        "products":        "الخدمات الطبية",
        "category":        "التخصص",
        "invoice":         "فاتورة طبية",
        "order":           "موعد / فحص",
        "new_order":       "حجز موعد جديد",
        "new_sale":        "فاتورة طبية جديدة",
        "new_invoice":     "فاتورة طبية جديدة",
        "item":            "إجراء / خدمة",
        "items":           "الإجراءات والخدمات",
        "customer":        "مريض",
        "customers":       "المرضى",
        "seller":          "طبيب",
        "employee":        "طاقم طبي",
        "cashier":         "محاسب العيادة",
        "unit":            "جلسة / زيارة",
        "work_order":      "ملف المريض",
        "project":         "خطة العلاج",
        "warehouse":       "مخزن المستلزمات",
        "stock":           "مخزون المستلزمات الطبية",
        "pos_mode":        "medical",
        "pos_search_hint": "ابحث بالخدمة أو اسم المريض...",
        "pos_quick_label": "فاتورة طبية",
        "industry_icon":   "🏥",
        "industry_label":  "عيادة / مستشفى",
    },
    "services": {
        "product":         "خدمة",
        "products":        "قائمة الخدمات",
        "category":        "نوع الخدمة",
        "invoice":         "فاتورة خدمة",
        "order":           "طلب خدمة",
        "new_order":       "طلب خدمة جديد",
        "new_sale":        "فاتورة جديدة",
        "item":            "خدمة",
        "items":           "الخدمات",
        "customer":        "عميل",
        "seller":          "موظف",
        "unit":            "ساعة / جلسة",
        "warehouse":       "—",
        "stock":           "—",
        "pos_mode":        "standard",
        "pos_search_hint": "ابحث بالخدمة أو العميل...",
        "pos_quick_label": "فاتورة جديدة",
        "industry_icon":   "🛠️",
        "industry_label":  "خدمات عامة",
    },
}


# ═══════════════════════════════════════════════════════════════════════════════
# منطق التحليل الذكي — يجد أقرب تطابق لأي industry_type
# ═══════════════════════════════════════════════════════════════════════════════

def _resolve_sector(industry_type: str) -> str:
    """
    يُحوّل industry_type إلى مفتاح قاموس المصطلحات بطريقة ذكية:
    1. مطابقة مباشرة (retail_health_pharmacy)
    2. تقليص تدريجي للـ prefix (retail_construction_materials → retail_construction → retail)
    3. قطاع افتراضي
    """
    if not industry_type:
        return "_default"

    # المطابقة المباشرة أولاً
    if industry_type in _SECTOR_TERMS:
        return industry_type

    # تقليص تدريجي: retail_fashion_clothing_m → retail_fashion_clothing → retail_fashion → retail
    parts = industry_type.split("_")
    for n in range(len(parts) - 1, 0, -1):
        candidate = "_".join(parts[:n])
        if candidate in _SECTOR_TERMS:
            return candidate

    return "_default"


def get_terms(industry_type: str) -> dict:
    """
    يُعيد قاموس مصطلحات مدمج (الافتراضي + تخصيص القطاع).
    أي مفتاح غير موجود في القطاع يُعاد من _DEFAULT.
    """
    sector = _resolve_sector(industry_type or "")
    custom = _SECTOR_TERMS.get(sector, {})
    return {**_DEFAULT, **custom}


def t(key: str, industry_type: str) -> str:
    """
    اختصار للحصول على مصطلح واحد.

    أمثلة:
        t("product",  "retail_health_pharmacy")    →  "دواء / مستحضر"
        t("seller",   "retail_auto_workshop")      →  "فني"
        t("customer", "food_restaurant")           →  "ضيف"
        t("invoice",  "construction")              →  "مستخلص مدفوعات"
        t("pos_mode", "retail_health_pharmacy")    →  "pharmacy"
    """
    return get_terms(industry_type).get(key, _DEFAULT.get(key, key))


def inject_terminology(industry_type: str) -> dict:
    """
    Context processor — يُضاف تلقائياً لجميع القوالب.

    في القالب:
        {{ T.product }}        → "طبق" (مطعم) / "دواء" (صيدلية) / "صنف" (سوبر ماركت)
        {{ T.seller }}         → "نادل" / "صيدلي" / "فني"
        {{ T.pos_mode }}       → "restaurant" / "pharmacy" / "workshop"
        {{ T.industry_icon }}  → "🍽️" / "💊" / "🔧"
    """
    return {"T": get_terms(industry_type)}
